# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3c5f9ebf694ac447ab467ba634d850cb8bc72bba9ee941958c4bd83506e553b064eab498e6c06aab6edab6a2c373d57e4a9a7a51aa86dcfe28b49a5841b6c16

test:
  secret_key_base: d7d67a5c55daf176291527015931d1631f0019d6a11fc9a8646e8a9e21b54c9aa366697504a424d04ba456a50bfe4480b9e5862b5fb270c4f7dc6fa58d2c0c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
